name: My First Workflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyfirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello world"
      - run: cargo --version

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List
        run: |
          echo "Runnnig tree"
          tree
